--------------------------------------------------------
--  File created - Wednesday-September-11-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table HISTORICALHDFCDATA
--------------------------------------------------------

  CREATE TABLE "DATA_OWNER"."HISTORICALHDFCDATA" 
   (	"DATE_STOCK" VARCHAR2(20 BYTE), 
	"SYMBOL" VARCHAR2(20 BYTE), 
	"CLOSE_PRICE" FLOAT(126)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into DATA_OWNER.HISTORICALHDFCDATA
SET DEFINE OFF;
Insert into DATA_OWNER.HISTORICALHDFCDATA (DATE_STOCK,SYMBOL,CLOSE_PRICE) values ('9-Sep-19',' HDFC',2064.25);
Insert into DATA_OWNER.HISTORICALHDFCDATA (DATE_STOCK,SYMBOL,CLOSE_PRICE) values ('6-Sep-19',' HDFC',2041.45);
Insert into DATA_OWNER.HISTORICALHDFCDATA (DATE_STOCK,SYMBOL,CLOSE_PRICE) values ('5-Sep-19',' HDFC',2044.15);
Insert into DATA_OWNER.HISTORICALHDFCDATA (DATE_STOCK,SYMBOL,CLOSE_PRICE) values ('4-Sep-19',' HDFC',2100.1);
Insert into DATA_OWNER.HISTORICALHDFCDATA (DATE_STOCK,SYMBOL,CLOSE_PRICE) values ('3-Sep-19',' HDFC',2089.9);
Insert into DATA_OWNER.HISTORICALHDFCDATA (DATE_STOCK,SYMBOL,CLOSE_PRICE) values ('30-Aug-19',' HDFC',2166.45);
Insert into DATA_OWNER.HISTORICALHDFCDATA (DATE_STOCK,SYMBOL,CLOSE_PRICE) values ('29-Aug-19',' HDFC',2128.45);
Insert into DATA_OWNER.HISTORICALHDFCDATA (DATE_STOCK,SYMBOL,CLOSE_PRICE) values ('28-Aug-19',' HDFC',2187.15);
Insert into DATA_OWNER.HISTORICALHDFCDATA (DATE_STOCK,SYMBOL,CLOSE_PRICE) values ('27-Aug-19',' HDFC',2174.3);
Insert into DATA_OWNER.HISTORICALHDFCDATA (DATE_STOCK,SYMBOL,CLOSE_PRICE) values ('26-Aug-19',' HDFC',2148.35);
Insert into DATA_OWNER.HISTORICALHDFCDATA (DATE_STOCK,SYMBOL,CLOSE_PRICE) values ('23-Aug-19',' HDFC',2043.75);
Insert into DATA_OWNER.HISTORICALHDFCDATA (DATE_STOCK,SYMBOL,CLOSE_PRICE) values ('22-Aug-19',' HDFC',2014.1);
Insert into DATA_OWNER.HISTORICALHDFCDATA (DATE_STOCK,SYMBOL,CLOSE_PRICE) values ('21-Aug-19',' HDFC',2066.9);
Insert into DATA_OWNER.HISTORICALHDFCDATA (DATE_STOCK,SYMBOL,CLOSE_PRICE) values ('20-Aug-19',' HDFC',2090.1);
Insert into DATA_OWNER.HISTORICALHDFCDATA (DATE_STOCK,SYMBOL,CLOSE_PRICE) values ('19-Aug-19',' HDFC',2114.05);
Insert into DATA_OWNER.HISTORICALHDFCDATA (DATE_STOCK,SYMBOL,CLOSE_PRICE) values ('16-Aug-19',' HDFC',2100);
Insert into DATA_OWNER.HISTORICALHDFCDATA (DATE_STOCK,SYMBOL,CLOSE_PRICE) values ('14-Aug-19',' HDFC',2117.7);
Insert into DATA_OWNER.HISTORICALHDFCDATA (DATE_STOCK,SYMBOL,CLOSE_PRICE) values ('13-Aug-19',' HDFC',2100.1);
Insert into DATA_OWNER.HISTORICALHDFCDATA (DATE_STOCK,SYMBOL,CLOSE_PRICE) values ('9-Aug-19',' HDFC',2211.65);
Insert into DATA_OWNER.HISTORICALHDFCDATA (DATE_STOCK,SYMBOL,CLOSE_PRICE) values ('8-Aug-19',' HDFC',2182.3);
Insert into DATA_OWNER.HISTORICALHDFCDATA (DATE_STOCK,SYMBOL,CLOSE_PRICE) values ('7-Aug-19',' HDFC',2175.2);
Insert into DATA_OWNER.HISTORICALHDFCDATA (DATE_STOCK,SYMBOL,CLOSE_PRICE) values ('6-Aug-19',' HDFC',2189.9);
Insert into DATA_OWNER.HISTORICALHDFCDATA (DATE_STOCK,SYMBOL,CLOSE_PRICE) values ('5-Aug-19',' HDFC',2152.35);
Insert into DATA_OWNER.HISTORICALHDFCDATA (DATE_STOCK,SYMBOL,CLOSE_PRICE) values ('2-Aug-19',' HDFC',2124.8);
Insert into DATA_OWNER.HISTORICALHDFCDATA (DATE_STOCK,SYMBOL,CLOSE_PRICE) values ('1-Aug-19',' HDFC',2086.8);
Insert into DATA_OWNER.HISTORICALHDFCDATA (DATE_STOCK,SYMBOL,CLOSE_PRICE) values ('31-Jul-19',' HDFC',2121.8);
Insert into DATA_OWNER.HISTORICALHDFCDATA (DATE_STOCK,SYMBOL,CLOSE_PRICE) values ('30-Jul-19',' HDFC',2127.25);
Insert into DATA_OWNER.HISTORICALHDFCDATA (DATE_STOCK,SYMBOL,CLOSE_PRICE) values ('29-Jul-19',' HDFC',2149);
Insert into DATA_OWNER.HISTORICALHDFCDATA (DATE_STOCK,SYMBOL,CLOSE_PRICE) values ('26-Jul-19',' HDFC',2165.75);
Insert into DATA_OWNER.HISTORICALHDFCDATA (DATE_STOCK,SYMBOL,CLOSE_PRICE) values ('25-Jul-19',' HDFC',2195.35);
Insert into DATA_OWNER.HISTORICALHDFCDATA (DATE_STOCK,SYMBOL,CLOSE_PRICE) values ('24-Jul-19',' HDFC',2184.25);
Insert into DATA_OWNER.HISTORICALHDFCDATA (DATE_STOCK,SYMBOL,CLOSE_PRICE) values ('23-Jul-19',' HDFC',2138.5);
Insert into DATA_OWNER.HISTORICALHDFCDATA (DATE_STOCK,SYMBOL,CLOSE_PRICE) values ('22-Jul-19',' HDFC',2186.9);
Insert into DATA_OWNER.HISTORICALHDFCDATA (DATE_STOCK,SYMBOL,CLOSE_PRICE) values ('19-Jul-19',' HDFC',2303.55);
Insert into DATA_OWNER.HISTORICALHDFCDATA (DATE_STOCK,SYMBOL,CLOSE_PRICE) values ('18-Jul-19',' HDFC',2345.15);
Insert into DATA_OWNER.HISTORICALHDFCDATA (DATE_STOCK,SYMBOL,CLOSE_PRICE) values ('17-Jul-19',' HDFC',2286.7);
Insert into DATA_OWNER.HISTORICALHDFCDATA (DATE_STOCK,SYMBOL,CLOSE_PRICE) values ('16-Jul-19',' HDFC',2277.55);
Insert into DATA_OWNER.HISTORICALHDFCDATA (DATE_STOCK,SYMBOL,CLOSE_PRICE) values ('15-Jul-19',' HDFC',2265.35);
Insert into DATA_OWNER.HISTORICALHDFCDATA (DATE_STOCK,SYMBOL,CLOSE_PRICE) values ('12-Jul-19',' HDFC',2257.8);
Insert into DATA_OWNER.HISTORICALHDFCDATA (DATE_STOCK,SYMBOL,CLOSE_PRICE) values ('11-Jul-19',' HDFC',2261.9);
Insert into DATA_OWNER.HISTORICALHDFCDATA (DATE_STOCK,SYMBOL,CLOSE_PRICE) values ('10-Jul-19',' HDFC',2227.75);
Insert into DATA_OWNER.HISTORICALHDFCDATA (DATE_STOCK,SYMBOL,CLOSE_PRICE) values ('9-Jul-19',' HDFC',2232.8);
Insert into DATA_OWNER.HISTORICALHDFCDATA (DATE_STOCK,SYMBOL,CLOSE_PRICE) values ('8-Jul-19',' HDFC',2259.95);
Insert into DATA_OWNER.HISTORICALHDFCDATA (DATE_STOCK,SYMBOL,CLOSE_PRICE) values ('5-Jul-19',' HDFC',2278.9);
Insert into DATA_OWNER.HISTORICALHDFCDATA (DATE_STOCK,SYMBOL,CLOSE_PRICE) values ('4-Jul-19',' HDFC',2280.25);
Insert into DATA_OWNER.HISTORICALHDFCDATA (DATE_STOCK,SYMBOL,CLOSE_PRICE) values ('3-Jul-19',' HDFC',2277.2);
Insert into DATA_OWNER.HISTORICALHDFCDATA (DATE_STOCK,SYMBOL,CLOSE_PRICE) values ('2-Jul-19',' HDFC',2281.25);
Insert into DATA_OWNER.HISTORICALHDFCDATA (DATE_STOCK,SYMBOL,CLOSE_PRICE) values ('1-Jul-19',' HDFC',2245.9);
Insert into DATA_OWNER.HISTORICALHDFCDATA (DATE_STOCK,SYMBOL,CLOSE_PRICE) values ('28-Jun-19',' HDFC',2192.1);
Insert into DATA_OWNER.HISTORICALHDFCDATA (DATE_STOCK,SYMBOL,CLOSE_PRICE) values ('27-Jun-19',' HDFC',2195.45);
Insert into DATA_OWNER.HISTORICALHDFCDATA (DATE_STOCK,SYMBOL,CLOSE_PRICE) values ('26-Jun-19',' HDFC',2168.1);
Insert into DATA_OWNER.HISTORICALHDFCDATA (DATE_STOCK,SYMBOL,CLOSE_PRICE) values ('25-Jun-19',' HDFC',2172.8);
Insert into DATA_OWNER.HISTORICALHDFCDATA (DATE_STOCK,SYMBOL,CLOSE_PRICE) values ('24-Jun-19',' HDFC',2148.9);
Insert into DATA_OWNER.HISTORICALHDFCDATA (DATE_STOCK,SYMBOL,CLOSE_PRICE) values ('21-Jun-19',' HDFC',2140.8);
Insert into DATA_OWNER.HISTORICALHDFCDATA (DATE_STOCK,SYMBOL,CLOSE_PRICE) values ('20-Jun-19',' HDFC',2199.25);
Insert into DATA_OWNER.HISTORICALHDFCDATA (DATE_STOCK,SYMBOL,CLOSE_PRICE) values ('19-Jun-19',' HDFC',2175.4);
Insert into DATA_OWNER.HISTORICALHDFCDATA (DATE_STOCK,SYMBOL,CLOSE_PRICE) values ('18-Jun-19',' HDFC',2153);
Insert into DATA_OWNER.HISTORICALHDFCDATA (DATE_STOCK,SYMBOL,CLOSE_PRICE) values ('17-Jun-19',' HDFC',2173);
Insert into DATA_OWNER.HISTORICALHDFCDATA (DATE_STOCK,SYMBOL,CLOSE_PRICE) values ('14-Jun-19',' HDFC',2185.85);
Insert into DATA_OWNER.HISTORICALHDFCDATA (DATE_STOCK,SYMBOL,CLOSE_PRICE) values ('13-Jun-19',' HDFC',2197.5);
Insert into DATA_OWNER.HISTORICALHDFCDATA (DATE_STOCK,SYMBOL,CLOSE_PRICE) values ('12-Jun-19',' HDFC',2181.95);
Insert into DATA_OWNER.HISTORICALHDFCDATA (DATE_STOCK,SYMBOL,CLOSE_PRICE) values ('11-Jun-19',' HDFC',2189.85);
--------------------------------------------------------
--  Constraints for Table HISTORICALHDFCDATA
--------------------------------------------------------

  ALTER TABLE "DATA_OWNER"."HISTORICALHDFCDATA" MODIFY ("CLOSE_PRICE" NOT NULL ENABLE);
  ALTER TABLE "DATA_OWNER"."HISTORICALHDFCDATA" MODIFY ("SYMBOL" NOT NULL ENABLE);
  ALTER TABLE "DATA_OWNER"."HISTORICALHDFCDATA" MODIFY ("DATE_STOCK" NOT NULL ENABLE);
