--------------------------------------------------------
--  File created - Monday-September-09-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table HOLDINGS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."HOLDINGS" 
   (	"EMAILID" VARCHAR2(30 BYTE), 
	"SYMBOL" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(3 BYTE), 
	"POSITION" VARCHAR2(5 BYTE), 
	"EXPIRY_DATE" VARCHAR2(30 BYTE), 
	"STRIKE_PRICE" NUMBER(8,2), 
	"LOT_SIZE" NUMBER(*,0), 
	"LOTS" NUMBER(*,0), 
	"PREMIUM" NUMBER(8,2) default null, 
	"LCP" NUMBER(8,2), 
	"AVG_PRICE" NUMBER(8,2) default null
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.HOLDINGS
SET DEFINE OFF;
Insert into SYSTEM.HOLDINGS (EMAILID,SYMBOL,TYPE,POSITION,EXPIRY_DATE,STRIKE_PRICE,LOT_SIZE,LOTS,PREMIUM,LCP,AVG_PRICE) values ('sailimaye@gmail.com','HDFCBANK','CE','LONG','26-SEP-19',2060,250,4,207.75,207.75,210.6);
Insert into SYSTEM.HOLDINGS (EMAILID,SYMBOL,TYPE,POSITION,EXPIRY_DATE,STRIKE_PRICE,LOT_SIZE,LOTS,PREMIUM,LCP,AVG_PRICE) values ('chandaknihal231@gmail.com','HDFCBANK','PE','SHORT','26-SEP-19',2220,250,2,25.5,32.35,31.5);
Insert into SYSTEM.HOLDINGS (EMAILID,SYMBOL,TYPE,POSITION,EXPIRY_DATE,STRIKE_PRICE,LOT_SIZE,LOTS,PREMIUM,LCP,AVG_PRICE) values ('sailimaye@gmail.com','HDFCBANK','PE','LONG','26-SEP-19',2100,250,2,4.1,6.6,3.8);
--------------------------------------------------------
--  Ref Constraints for Table HOLDINGS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."HOLDINGS" ADD FOREIGN KEY ("EMAILID")
	  REFERENCES "SYSTEM"."USERS" ("EMAILID") ENABLE;
