--------------------------------------------------------
--  File created - Thursday-September-12-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table HOLDINGS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."HOLDINGS" 
   (	"EMAILID" VARCHAR2(30 BYTE), 
	"SYMBOL" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(3 BYTE), 
	"POSITION" VARCHAR2(5 BYTE), 
	"EXPIRY_DATE" VARCHAR2(30 BYTE), 
	"STRIKE_PRICE" NUMBER(8,2), 
	"LOT_SIZE" NUMBER(*,0), 
	"LOTS" NUMBER(*,0), 
	"PREMIUM" NUMBER(8,2) DEFAULT null, 
	"LCP" NUMBER(8,2), 
	"AVG_PRICE" NUMBER(8,2) DEFAULT null
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.HOLDINGS
SET DEFINE OFF;
Insert into SYSTEM.HOLDINGS (EMAILID,SYMBOL,TYPE,POSITION,EXPIRY_DATE,STRIKE_PRICE,LOT_SIZE,LOTS,PREMIUM,LCP,AVG_PRICE) values ('joesanthosh@yahoo.com','HDFCBANK','CE','LONG','26-SEP-19',2060,250,4,207.75,207.75,0);
Insert into SYSTEM.HOLDINGS (EMAILID,SYMBOL,TYPE,POSITION,EXPIRY_DATE,STRIKE_PRICE,LOT_SIZE,LOTS,PREMIUM,LCP,AVG_PRICE) values ('apoorva@gmail.com','HDFCBANK','CE','SHORT','26-SEP-19',2220,250,2,58.65,56.1,0);
Insert into SYSTEM.HOLDINGS (EMAILID,SYMBOL,TYPE,POSITION,EXPIRY_DATE,STRIKE_PRICE,LOT_SIZE,LOTS,PREMIUM,LCP,AVG_PRICE) values ('joesanthosh@yahoo.com','HDFCBANK','CE','LONG','26-SEP-19',2100,250,2,161.05,161.05,0);
Insert into SYSTEM.HOLDINGS (EMAILID,SYMBOL,TYPE,POSITION,EXPIRY_DATE,STRIKE_PRICE,LOT_SIZE,LOTS,PREMIUM,LCP,AVG_PRICE) values ('suraj@gmail.com','ITC','FUT','LONG','28-NOV-19',0,2400,4,0,222,221);
Insert into SYSTEM.HOLDINGS (EMAILID,SYMBOL,TYPE,POSITION,EXPIRY_DATE,STRIKE_PRICE,LOT_SIZE,LOTS,PREMIUM,LCP,AVG_PRICE) values ('joesanthosh@yahoo.com','RELIANCE','CE','LONG','31-OCT-19',1080,500,5,146,145,0);
Insert into SYSTEM.HOLDINGS (EMAILID,SYMBOL,TYPE,POSITION,EXPIRY_DATE,STRIKE_PRICE,LOT_SIZE,LOTS,PREMIUM,LCP,AVG_PRICE) values ('apoorva@gmail.com','ITC','PE','SHORT','26-SEP-19',230,2400,2,1.2,0.8,0);
Insert into SYSTEM.HOLDINGS (EMAILID,SYMBOL,TYPE,POSITION,EXPIRY_DATE,STRIKE_PRICE,LOT_SIZE,LOTS,PREMIUM,LCP,AVG_PRICE) values ('joesanthosh@yahoo.com','RELIANCE','CE','LONG','26-SEP-19',1120,500,6,132.5,134.5,0);
Insert into SYSTEM.HOLDINGS (EMAILID,SYMBOL,TYPE,POSITION,EXPIRY_DATE,STRIKE_PRICE,LOT_SIZE,LOTS,PREMIUM,LCP,AVG_PRICE) values ('suraj@gmail.com','INFY','CE','LONG','26-SEP-19',740,1200,4,108,105,0);
Insert into SYSTEM.HOLDINGS (EMAILID,SYMBOL,TYPE,POSITION,EXPIRY_DATE,STRIKE_PRICE,LOT_SIZE,LOTS,PREMIUM,LCP,AVG_PRICE) values ('joesanthosh@yahoo.com','INFY','CE','LONG','26-SEP-19',740,1200,7,108,105,0);
Insert into SYSTEM.HOLDINGS (EMAILID,SYMBOL,TYPE,POSITION,EXPIRY_DATE,STRIKE_PRICE,LOT_SIZE,LOTS,PREMIUM,LCP,AVG_PRICE) values ('suraj@gmail.com','SUNPHARMA','FUT','LONG','28-NOV-19',0,1100,4,0,372,374);
Insert into SYSTEM.HOLDINGS (EMAILID,SYMBOL,TYPE,POSITION,EXPIRY_DATE,STRIKE_PRICE,LOT_SIZE,LOTS,PREMIUM,LCP,AVG_PRICE) values ('apoorva@gmail.com','ITC','PE','SHORT','31-OCT-19',235,2400,5,2.1,1.1,0);
Insert into SYSTEM.HOLDINGS (EMAILID,SYMBOL,TYPE,POSITION,EXPIRY_DATE,STRIKE_PRICE,LOT_SIZE,LOTS,PREMIUM,LCP,AVG_PRICE) values ('apoorva@gmail.com','RELIANCE','PE','LONG','31-OCT-19',1120,500,6,3,2.5,0);
Insert into SYSTEM.HOLDINGS (EMAILID,SYMBOL,TYPE,POSITION,EXPIRY_DATE,STRIKE_PRICE,LOT_SIZE,LOTS,PREMIUM,LCP,AVG_PRICE) values ('apoorva@gmail.com','INFY','PE','LONG','31-OCT-19',820,1200,4,16,15,0);
Insert into SYSTEM.HOLDINGS (EMAILID,SYMBOL,TYPE,POSITION,EXPIRY_DATE,STRIKE_PRICE,LOT_SIZE,LOTS,PREMIUM,LCP,AVG_PRICE) values ('apoorva@gmail.com','INFY','CE','LONG','26-SEP-19',800,1200,7,34,31.5,0);
Insert into SYSTEM.HOLDINGS (EMAILID,SYMBOL,TYPE,POSITION,EXPIRY_DATE,STRIKE_PRICE,LOT_SIZE,LOTS,PREMIUM,LCP,AVG_PRICE) values ('utkarsh1@yahoo.com','ITC','CE','LONG','26-SEP-19',235,2400,5,18.75,15.75,0);
Insert into SYSTEM.HOLDINGS (EMAILID,SYMBOL,TYPE,POSITION,EXPIRY_DATE,STRIKE_PRICE,LOT_SIZE,LOTS,PREMIUM,LCP,AVG_PRICE) values ('utkarsh1@yahoo.com','RELIANCE','PE','SHORT','28-NOV-19',1160,500,8,7.25,6,0);
Insert into SYSTEM.HOLDINGS (EMAILID,SYMBOL,TYPE,POSITION,EXPIRY_DATE,STRIKE_PRICE,LOT_SIZE,LOTS,PREMIUM,LCP,AVG_PRICE) values ('utkarsh1@yahoo.com','INFY','PE','SHORT','31-OCT-19',860,1200,4,52.2,47.2,0);
Insert into SYSTEM.HOLDINGS (EMAILID,SYMBOL,TYPE,POSITION,EXPIRY_DATE,STRIKE_PRICE,LOT_SIZE,LOTS,PREMIUM,LCP,AVG_PRICE) values ('utkarsh1@yahoo.com','INFY','CE','LONG','26-SEP-19',800,1200,6,34,31.5,0);
Insert into SYSTEM.HOLDINGS (EMAILID,SYMBOL,TYPE,POSITION,EXPIRY_DATE,STRIKE_PRICE,LOT_SIZE,LOTS,PREMIUM,LCP,AVG_PRICE) values ('utkarsh1@yahoo.com','SUNPHARMA','FUT','LONG','31-OCT-19',0,1100,4,0,405,400);
--------------------------------------------------------
--  Ref Constraints for Table HOLDINGS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."HOLDINGS" ADD FOREIGN KEY ("EMAILID")
	  REFERENCES "SYSTEM"."USERS" ("EMAILID") ENABLE;
