--------------------------------------------------------
--  File created - Wednesday-September-11-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table HOLDINGS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."HOLDINGS" 
   (	"EMAILID" VARCHAR2(30 BYTE), 
	"SYMBOL" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(3 BYTE), 
	"POSITION" VARCHAR2(5 BYTE), 
	"EXPIRY_DATE" VARCHAR2(30 BYTE), 
	"STRIKE_PRICE" NUMBER(8,2), 
	"LOT_SIZE" NUMBER(*,0), 
	"LOTS" NUMBER(*,0), 
	"PREMIUM" NUMBER(8,2) DEFAULT null, 
	"LCP" NUMBER(8,2), 
	"AVG_PRICE" NUMBER(8,2) DEFAULT null
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.HOLDINGS
SET DEFINE OFF;
Insert into SYSTEM.HOLDINGS (EMAILID,SYMBOL,TYPE,POSITION,EXPIRY_DATE,STRIKE_PRICE,LOT_SIZE,LOTS,PREMIUM,LCP,AVG_PRICE) values ('sailimaye@gmail.com','HDFCBANK','CE','LONG','26-SEP-19',2060,250,4,207.75,207.75,0);
Insert into SYSTEM.HOLDINGS (EMAILID,SYMBOL,TYPE,POSITION,EXPIRY_DATE,STRIKE_PRICE,LOT_SIZE,LOTS,PREMIUM,LCP,AVG_PRICE) values ('chandaknihal231@gmail.com','HDFCBANK','PE','SHORT','26-SEP-19',2220,250,2,25.5,32.35,0);
Insert into SYSTEM.HOLDINGS (EMAILID,SYMBOL,TYPE,POSITION,EXPIRY_DATE,STRIKE_PRICE,LOT_SIZE,LOTS,PREMIUM,LCP,AVG_PRICE) values ('sailimaye@gmail.com','HDFCBANK','PE','LONG','26-SEP-19',2100,250,2,4.1,6.6,0);
Insert into SYSTEM.HOLDINGS (EMAILID,SYMBOL,TYPE,POSITION,EXPIRY_DATE,STRIKE_PRICE,LOT_SIZE,LOTS,PREMIUM,LCP,AVG_PRICE) values ('utkarshsharmaas@gmail.com','ITC','FUT','LONG','28-NOV-19',225,2400,4,6.5,222,221);
Insert into SYSTEM.HOLDINGS (EMAILID,SYMBOL,TYPE,POSITION,EXPIRY_DATE,STRIKE_PRICE,LOT_SIZE,LOTS,PREMIUM,LCP,AVG_PRICE) values ('sailimaye@gmail.com','RELIANCE','CE','LONG','31-OCT-19',1080,500,5,8.6,1105.5,0);
Insert into SYSTEM.HOLDINGS (EMAILID,SYMBOL,TYPE,POSITION,EXPIRY_DATE,STRIKE_PRICE,LOT_SIZE,LOTS,PREMIUM,LCP,AVG_PRICE) values ('chandaknihal231@gmail.com','ITC','PE','SHORT','26-SEP-19',230,2400,2,11.5,233.5,0);
Insert into SYSTEM.HOLDINGS (EMAILID,SYMBOL,TYPE,POSITION,EXPIRY_DATE,STRIKE_PRICE,LOT_SIZE,LOTS,PREMIUM,LCP,AVG_PRICE) values ('sailimaye@gmail.com','RELIANCE','CE','LONG','26-SEP-19',1120,500,6,6.5,1112.5,0);
Insert into SYSTEM.HOLDINGS (EMAILID,SYMBOL,TYPE,POSITION,EXPIRY_DATE,STRIKE_PRICE,LOT_SIZE,LOTS,PREMIUM,LCP,AVG_PRICE) values ('utkarshsharmaas@gmail.com','INFY','CE','LONG','28-NOV-19',740,1200,4,6.5,742.5,0);
Insert into SYSTEM.HOLDINGS (EMAILID,SYMBOL,TYPE,POSITION,EXPIRY_DATE,STRIKE_PRICE,LOT_SIZE,LOTS,PREMIUM,LCP,AVG_PRICE) values ('sailimaye@gmail.com','INFY','PE','LONG','26-SEP-19',740,1200,7,4.1,735.5,0);
Insert into SYSTEM.HOLDINGS (EMAILID,SYMBOL,TYPE,POSITION,EXPIRY_DATE,STRIKE_PRICE,LOT_SIZE,LOTS,PREMIUM,LCP,AVG_PRICE) values ('utkarshsharmaas@gmail.com','SUNPHARMA','FUT','LONG','28-NOV-19',370,1100,4,8.1,372,374);
Insert into SYSTEM.HOLDINGS (EMAILID,SYMBOL,TYPE,POSITION,EXPIRY_DATE,STRIKE_PRICE,LOT_SIZE,LOTS,PREMIUM,LCP,AVG_PRICE) values ('19apoorva.v@gmail.com','ITC','PE','SHORT','31-OCT-19',235,2400,5,9.5,233.5,0);
Insert into SYSTEM.HOLDINGS (EMAILID,SYMBOL,TYPE,POSITION,EXPIRY_DATE,STRIKE_PRICE,LOT_SIZE,LOTS,PREMIUM,LCP,AVG_PRICE) values ('19apoorva.v@gmail.com','RELIANCE','PE','LONG','31-OCT-19',1120,500,6,6.5,1112.5,0);
Insert into SYSTEM.HOLDINGS (EMAILID,SYMBOL,TYPE,POSITION,EXPIRY_DATE,STRIKE_PRICE,LOT_SIZE,LOTS,PREMIUM,LCP,AVG_PRICE) values ('19apoorva.v@gmail.com','INFY','CE','LONG','31-OCT-19',820,1200,4,7.1,792.5,0);
Insert into SYSTEM.HOLDINGS (EMAILID,SYMBOL,TYPE,POSITION,EXPIRY_DATE,STRIKE_PRICE,LOT_SIZE,LOTS,PREMIUM,LCP,AVG_PRICE) values ('19apoorva.v@gmail.com','INFY','PE','LONG','26-SEP-19',800,1200,7,11.5,805,0);
Insert into SYSTEM.HOLDINGS (EMAILID,SYMBOL,TYPE,POSITION,EXPIRY_DATE,STRIKE_PRICE,LOT_SIZE,LOTS,PREMIUM,LCP,AVG_PRICE) values ('19apoorva.v@gmail.com','SUNPHARMA','FUT','LONG','28-NOV-19',390,1100,4,8.1,399,395);
Insert into SYSTEM.HOLDINGS (EMAILID,SYMBOL,TYPE,POSITION,EXPIRY_DATE,STRIKE_PRICE,LOT_SIZE,LOTS,PREMIUM,LCP,AVG_PRICE) values ('shantanu.vijay8@gmail.com','ITC','CE','LONG','26-SEP-19',235,2400,5,9.5,233.5,0);
Insert into SYSTEM.HOLDINGS (EMAILID,SYMBOL,TYPE,POSITION,EXPIRY_DATE,STRIKE_PRICE,LOT_SIZE,LOTS,PREMIUM,LCP,AVG_PRICE) values ('shantanu.vijay8@gmail.com','RELIANCE','PE','SHORT','28-NOV-19',1160,500,8,7.5,1152,0);
Insert into SYSTEM.HOLDINGS (EMAILID,SYMBOL,TYPE,POSITION,EXPIRY_DATE,STRIKE_PRICE,LOT_SIZE,LOTS,PREMIUM,LCP,AVG_PRICE) values ('shantanu.vijay8@gmail.com','INFY','CE','SHORT','31-OCT-19',860,1200,4,7.1,844,0);
Insert into SYSTEM.HOLDINGS (EMAILID,SYMBOL,TYPE,POSITION,EXPIRY_DATE,STRIKE_PRICE,LOT_SIZE,LOTS,PREMIUM,LCP,AVG_PRICE) values ('shantanu.vijay8@gmail.com','INFY','CE','LONG','26-SEP-19',800,1200,6,11.5,805,0);
Insert into SYSTEM.HOLDINGS (EMAILID,SYMBOL,TYPE,POSITION,EXPIRY_DATE,STRIKE_PRICE,LOT_SIZE,LOTS,PREMIUM,LCP,AVG_PRICE) values ('shantanu.vijay8@gmail.com','SUNPHARMA','FUT','LONG','31-OCT-19',410,1100,4,8.1,405,400);
--------------------------------------------------------
--  Ref Constraints for Table HOLDINGS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."HOLDINGS" ADD FOREIGN KEY ("EMAILID")
	  REFERENCES "SYSTEM"."USERS" ("EMAILID") ENABLE;
